=== BioAnalyticResource/Araport_eFP-Seq_Browser/app/data/bamdata_amazon_links.dtd
<!ELEMENT rnaseq_experiments (bam_file)+>
	<!ELEMENT bam_file (controls, groupwith)>
		<!ATTLIST bam_file 
			title CDATA #REQUIRED 
			publication_url CDATA #REQUIRED 
			svgname CDATA #REQUIRED 
			svg_subunit CDATA #REQUIRED 
			desc CDATA #REQUIRED 
			record_number CDATA #REQUIRED 
			hex_colour CDATA #REQUIRED 
			bam_link CDATA #REQUIRED 
			total_reads_mapped CDATA #REQUIRED 
			publication_link CDATA #REQUIRED>
<!ELEMENT controls (bam_exp+)>
<!ELEMENT groupwith (bam_exp+)>
<!ELEMENT bam_exp (#PCDATA)>

=== BioAnalyticResource/Araport_eFP-Seq_Browser/app/data/bamdata_amazon_links.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE rnaseq_experiments SYSTEM "app/data/bamdata_amazon_links.dtd">
    <rnaseq_experiments>
        <bam_file desc="E-MTAB-1668:24hCS-RNA" record_number="ERR274310" hex_colour="0x64cc65" bam_link="http://s3.amazonaws.com/iplant-cdn/iplant/home/araport/rnaseq_bam/aerial/ERR274310/accepted_hits.bam" total_reads_mapped="29098868" publication_link="http://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-1668/" svg_subunit="shoot" svgname="ath-rosettePlusRoot.svg" title="Aerial part of long-day-grown 4-leaf-stage seedling with mock (NaCl) treatment" publication_url="http://www.ncbi.nlm.nih.gov/Traces/sra/?run=ERR274310">
            <controls>
                <bam_exp>ERR274310</bam_exp>
            </controls>
            <groupwith>
                <bam_exp>ERR274308</bam_exp>
                <bam_exp>ERR274309</bam_exp>
                <bam_exp>ERR274310</bam_exp>
                <bam_exp>ERR274311</bam_exp>
            </groupwith>
        </bam_file>
        <bam_file desc="GSM798296: mRNASeq_WT_rep2" record_number="SRR547531" hex_colour="0x64cc65" bam_link="http://s3.amazonaws.com/iplant-cdn/iplant/home/araport/rnaseq_bam/aerial/SRR547531/accepted_hits.bam" total_reads_mapped="13627154" publication_link="http://www.ncbi.nlm.nih.gov/pubmed/23349984" svg_subunit="shoot" svgname="ath-rosettePlusRoot.svg" title="Transcription profiling of Arabidopsis plants overexpressing SlHsfA3 (thale cress)" publication_url="http://www.ncbi.nlm.nih.gov/Traces/sra/?run=SRR547531">
            <controls>
                <bam_exp>SRR547531</bam_exp>
            </controls>
            <groupwith>
                <bam_exp>SRR547531</bam_exp>
                <bam_exp>SRR547532</bam_exp>
                <bam_exp>SRR547533</bam_exp>
            </groupwith>
        </bam_file>
        <bam_file desc="GSM994838; SRA: SRS360059" record_number="SRR548277" hex_colour="0x64cc65" bam_link="http://s3.amazonaws.com/iplant-cdn/iplant/home/araport/rnaseq_bam/aerial/SRR548277/accepted_hits.bam" total_reads_mapped="10647001" publication_link="http://www.ncbi.nlm.nih.gov/pubmed/23755095" svg_subunit="shoot" svgname="ath-rosettePlusRoot.svg" title="Aerial part of 4-week-old plant" publication_url="http://www.ncbi.nlm.nih.gov/Traces/sra/?run=SRR548277">
            <controls>
                <bam_exp>SRR548277</bam_exp>
            </controls>
            <groupwith>
                <bam_exp>SRR548277</bam_exp>
                <bam_exp>SRR548278</bam_exp>
            </groupwith>
        </bam_file>
        <bam_file desc="Seedling1,SRA: SRS419144" record_number="SRR847503" hex_colour="0x64cc65" bam_link="http://s3.amazonaws.com/iplant-cdn/iplant/home/araport/rnaseq_bam/aerial/SRR847503/accepted_hits.bam" total_reads_mapped="19012222" publication_link="http://www.ncbi.nlm.nih.gov/pubmed/24792048" svg_subunit="shoot" svgname="ath-rosettePlusRoot.svg" title="Aerial part of 3-week-old soil-grown plant" publication_url="http://www.ncbi.nlm.nih.gov/Traces/sra/?run=SRR847503">
            <controls>
                <bam_exp>SRR847501</bam_exp>
                <bam_exp>SRR847502</bam_exp>
            </controls>
            <groupwith>
                <bam_exp>SRR847501</bam_exp>
                <bam_exp>SRR847502</bam_exp>
                <bam_exp>SRR847503</bam_exp>
                <bam_exp>SRR847504</bam_exp>
                <bam_exp>SRR847505</bam_exp>
                <bam_exp>SRR847506</bam_exp>
            </groupwith>
        </bam_file>
        <bam_file desc="Seedling1,SRA: SRS419144" record_number="SRR847504" hex_colour="0x64cc65" bam_link="http://s3.amazonaws.com/iplant-cdn/iplant/home/araport/rnaseq_bam/aerial/SRR847504/accepted_hits.bam" total_reads_mapped="17652623" publication_link="http://www.ncbi.nlm.nih.gov/pubmed/24792048" svg_subunit="shoot" svgname="ath-rosettePlusRoot.svg" title="Aerial part of 3-week-old soil-grown plant" publication_url="http://www.ncbi.nlm.nih.gov/Traces/sra/?run=SRR847504">
            <controls>
                <bam_exp>SRR847501</bam_exp>
                <bam_exp>SRR847502</bam_exp>
            </controls>
            <groupwith>
                <bam_exp>SRR847501</bam_exp>
                <bam_exp>SRR847502</bam_exp>
                <bam_exp>SRR847503</bam_exp>
                <bam_exp>SRR847504</bam_exp>
                <bam_exp>SRR847505</bam_exp>
                <bam_exp>SRR847506</bam_exp>
            </groupwith>
        </bam_file>
        <bam_file desc="Seedling2, SRA: SRS419145" record_number="SRR847505" hex_colour="0x64cc65" bam_link="http://s3.amazonaws.com/iplant-cdn/iplant/home/araport/rnaseq_bam/aerial/SRR847505/accepted_hits.bam" total_reads_mapped="14547829" publication_link="http://www.ncbi.nlm.nih.gov/pubmed/24792048" svg_subunit="shoot" svgname="ath-rosettePlusRoot.svg" title="Aerial part of 3-week-old soil-grown plant" publication_url="http://www.ncbi.nlm.nih.gov/Traces/sra/?run=SRR847505">
            <controls>
                <bam_exp>SRR847501</bam_exp>
                <bam_exp>SRR847502</bam_exp>
            </controls>
            <groupwith>
                <bam_exp>SRR847501</bam_exp>
                <bam_exp>SRR847502</bam_exp>
                <bam_exp>SRR847503</bam_exp>
                <bam_exp>SRR847504</bam_exp>
                <bam_exp>SRR847505</bam_exp>
                <bam_exp>SRR847506</bam_exp>
            </groupwith>
        </bam_file>
        <bam_file desc="Seedling2, SRA: SRS419145" record_number="SRR847506" hex_colour="0x64cc65" bam_link="http://s3.amazonaws.com/iplant-cdn/iplant/home/araport/rnaseq_bam/aerial/SRR847506/accepted_hits.bam" total_reads_mapped="14547829" publication_link="http://www.ncbi.nlm.nih.gov/pubmed/24792048" svg_subunit="shoot" svgname="ath-rosettePlusRoot.svg" title="Aerial part of 3-week-old soil-grown plant" publication_url="http://www.ncbi.nlm.nih.gov/Traces/sra/?run=SRR847506">
            <controls>
                <bam_exp>SRR847501</bam_exp>
                <bam_exp>SRR847502</bam_exp>
            </controls>
            <groupwith>
                <bam_exp>SRR847501</bam_exp>
                <bam_exp>SRR847502</bam_exp>
                <bam_exp>SRR847503</bam_exp>
                <bam_exp>SRR847504</bam_exp>
                <bam_exp>SRR847505</bam_exp>
                <bam_exp>SRR847506</bam_exp>
            </groupwith>
        </bam_file>
        <bam_file desc="carpel, GSM1359146, SRA: SRS583574" record_number="SRR1207194" hex_colour="0xFFFF00" bam_link="http://s3.amazonaws.com/iplant-cdn/iplant/home/araport/rnaseq_bam/carpel/SRR1207194/accepted_hits.bam" total_reads_mapped="41295666" svg_subunit="carpels" svgname="ath-FlowerParts.svg" title="Carpels collected manually from stage 8-13 flowers" publication_url="http://www.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1207194">
            <controls>
                <bam_exp>SRR1207194</bam_exp>
                <bam_exp>SRR1207195</bam_exp>
            </controls>
            <groupwith>
                <bam_exp>SRR1207194</bam_exp>
                <bam_exp>SRR1207195</bam_exp>
                <bam_exp>SRR1207196</bam_exp>
                <bam_exp>SRR1207197</bam_exp>
                <bam_exp>SRR1207198</bam_exp>
                <bam_exp>SRR1207199</bam_exp>
                <bam_exp>SRR1207200</bam_exp>
                <bam_exp>SRR1207201</bam_exp>
            </groupwith>
        </bam_file>
        <bam_file desc="carpel, GSM1359146, SRA: SRS583574" record_number="SRR1207195" hex_colour="0xFFFF00" bam_link="http://s3.amazonaws.com/iplant-cdn/iplant/home/araport/rnaseq_bam/carpel/SRR1207195/accepted_hits.bam" total_reads_mapped="39074103" svg_subunit="carpels" svgname="ath-FlowerParts.svg" title="Carpels collected manually from stage 8-13 flowers" publication_url="http://www.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1207195">
            <controls>
                <bam_exp>SRR1207194</bam_exp>
                <bam_exp>SRR1207195</bam_exp>
            </controls>
            <groupwith>
                <bam_exp>SRR1207194</bam_exp>
                <bam_exp>SRR1207195</bam_exp>
                <bam_exp>SRR1207196</bam_exp>
                <bam_exp>SRR1207197</bam_exp>
                <bam_exp>SRR1207198</bam_exp>
                <bam_exp>SRR1207199</bam_exp>
                <bam_exp>SRR1207200</bam_exp>
                <bam_exp>SRR1207201</bam_exp>
            </groupwith>
        </bam_file>
        <bam_file desc="Etiolated wild type (Col-0) seedlings, GSM1252262, SRA: SRS494530" record_number="SRR1019436" hex_colour="0xCCCC97" bam_link="http://s3.amazonaws.com/iplant-cdn/iplant/home/araport/rnaseq_bam/dark/SRR1019436/accepted_hits.bam" total_reads_mapped="22144930" publication_link="http://www.ncbi.nlm.nih.gov/pubmed/24867218" svg_subunit="etiolatedseedling" svgname="ath-etiolatedSeedling.svg" title="5do etiolated seedling" publication_url="http://www.ncbi.nlm.nih.gov/Traces/sra/?run=SRR1019436">
            <controls>
                <bam_exp>SRR1019436</bam_exp>
                <bam_exp>SRR1019437</bam_exp>
                <bam_exp>SRR1019438</bam_exp>
                <bam_exp>SRR1019439</bam_exp>
            </controls>
            <groupwith>
                <bam_exp>SRR1019436</bam_exp>
                <bam_exp>SRR1019437</bam_exp>
                <bam_exp>SRR1019438</bam_exp>
                <bam_exp>SRR1019439</bam_exp>
                <bam_exp>SRR1019440</bam_exp>
                <bam_exp>SRR1019441</bam_exp>
                <bam_exp>SRR1019442</bam_exp>
                <bam_exp>SRR1019443</bam_exp>
            </groupwith>
        </bam_file>
